version: '3.8'



services:
  web:
    #берем Dockerfile из каталога HR
    build: ./HR
    #запускаем тестовый сервер
    command: python3 manage.py runserver 0.0.0.0:7000
    #куда будут помущены данные из каталога HR
    volumes:
      - ./HR/:/usr/src/HR/
    # Открывем порт 8000 внутри и снаружи
    ports:
      - 7000:7000
    # Файл содержащий переменные для контейнера
    env_file: 
      - /HR/HR/.env
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

volumes:
  postgres_volume:
